### ISSUE TITLE
Menu Bug

### ISSUE THREAD

**Issue by XiNaru** [Nykal145/LuckSkill1.6#1]
Hey i want say/show you this

https://images.xinaru.de/index.php/s/GiiD4NaRPrExYkx/preview

the socializing and binning skill dont show up there, maybe until the spacecore fixed you does this too?

**Comment by Nykal145** [comment]
Spacecore removed a feature where you could add a skill to a different  UI. Once it is added back to spacecore I will update and fix the this but until then I want to keep it as is so its able to be seen by users.
