### ISSUE TITLE
Luck skill break mastery system

### ISSUE THREAD

**Issue by Genkail** [Nykal145/LuckSkill1.6#2]
The new skill system becomes unavailable if all skills are level 10.
The screenshot was made after the removal of luck skill, but the problem remains with its presence.
![image](https://github.com/Nykal145/LuckSkill1.6/assets/50331122/bca58b37-2793-4c81-a20a-c555c41ab85b)
If there are 10 professions together with luck skill, the skill scale is filled, but disappears when you get 11+

I apologize for my English, I use a translator

**Comment by Nykal145** [comment]
This should be resolved with the newest release, try updating and let me know if the issue persists.
